---
AWSTemplateFormatVersion: "2010-09-09"
Description: |
  VPC template


################################################################################
#                                  Metadata                                    #
################################################################################
Metadata: {}


################################################################################
#                               Parameters                                     #
################################################################################
Parameters: {}


################################################################################
#                               Resources                                      #
################################################################################
Resources:

  # DynamoDB - Table Sample
  DynamnoDBSampleTable:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
        HashKeyElement:
          AttributeName: "ID"
          AttributeType: "S"
        RangeKeyElement:
          AttributeName: "Username"
          AttributeType: "N"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "10"
      TableName: "deployerSampleTable"


################################################################################
#                                   Outputs                                    #
################################################################################
Outputs: {}